# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://rseed42.github.io/musicai/"

git_url = "https://github.com/rseed42/musicai/tree/master/"

def custom_doc_links(name): return None
